version: '3.7'

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    volumes:
      - ./createDbUser.js:/docker-entrypoint-initdb.d/createDbUser.js:ro 
volumes:
  mongodb:
