export const queryResults = {
  data: {
    info: [
			{
				cEffectiveness: 0,
				f1: 0.5,
				precision: 1,
				qEffectiveness: 0,
				recall: 1,
				score: 5,
				/*----------*/
				activeBm: 3,
				bmRelevant: 2,
				numQueries: 5,
				pageStay: 92.15,
				queryEntropy: 1.27125,
				totalCover: 10,
				totalModQuery: 9,
				usfCover: 7,
				writingTime: 45,
			},
			{
				cEffectiveness: 0.8,
				f1: 0.2,
				precision: 0.8,
				qEffectiveness: 0,
				recall: 0.2,
				score: 4.2,
				/*----------*/
				activeBm: 12,
				bmRelevant: 2,
				numQueries: 9,
				pageStay: 24.52,
				queryEntropy: 1.16289,
				totalCover: 6,
				totalModQuery: 8,
				usfCover: 7,
				writingTime: 35,
			},
			{
				cEffectiveness: 0.7,
				f1: 0.3,
				precision: 0.9,
				qEffectiveness: 0.4,
				recall: 0.6,
				score: 2.8,
				/*----------*/
				activeBm: 5,
				bmRelevant: 3,
				numQueries: 12,
				pageStay: 23.41,
				queryEntropy: 0.573,
				totalCover: 8,
				totalModQuery: 4,
				usfCover: 5,
				writingTime: 23,
			},
			{
				cEffectiveness: 0.1,
				f1: 0.7,
				precision: 0.6,
				qEffectiveness: 0.2,
				recall: 0.7,
				score: 5,
				/*----------*/
				activeBm: 8,
				bmRelevant: 2,
				numQueries: 14,
				pageStay: 26.36,
				queryEntropy: 0.573,
				totalCover: 7,
				totalModQuery: 7,
				usfCover: 4,
				writingTime: 32,
			},
			{
				cEffectiveness: 0.2,
				f1: 0.6,
				precision: 0.9,
				qEffectiveness: 0.4,
				recall: 0.3,
				score: 3.8,
				/*----------*/
				activeBm: 2,
				bmRelevant: 1,
				numQueries: 30,
				pageStay: 25.12,
				queryEntropy: 1.27125,
				totalCover: 1,
				totalModQuery: 4,
				usfCover: 12,
				writingTime: 27,
			},
			{
				cEffectiveness: 0.9,
				f1: 1,
				precision: 1,
				qEffectiveness: 0,
				recall: 0.4,
				score: 3.2,
				/*----------*/
				activeBm: 7,
				bmRelevant: 3,
				numQueries: 10,
				pageStay: 14.23,
				queryEntropy: 1.95345,
				totalCover: 11,
				totalModQuery: 6,
				usfCover: 11,
				writingTime: 37,
			},
			{
				cEffectiveness: 0.4,
				f1: 0.9,
				precision: 0.3,
				qEffectiveness: 0.1,
				recall: 0.7,
				score: 3.2,
				/*----------*/
				activeBm: 3,
				bmRelevant: 2,
				numQueries: 5,
				pageStay: 92.15,
				queryEntropy: 1.27125,
				totalCover: 10,
				totalModQuery: 5,
				usfCover: 6,
				writingTime: 23,
			},
			{
				cEffectiveness: 1,
				f1: 1,
				precision: 0.3,
				qEffectiveness: 0.9,
				recall: 1,
				score: 4.2,
				/*----------*/
				activeBm: 2,
				bmRelevant: 3,
				numQueries: 7,
				pageStay: 32.14,
				queryEntropy: 1.95345,
				totalCover: 7,
				totalModQuery: 4,
				usfCover: 4,
				writingTime: 17,
			},
			{
				cEffectiveness: 0.3,
				f1: 0.9,
				precision: 1,
				qEffectiveness: 0.7,
				recall: 0.5,
				score: 2.7,
				/*----------*/
				activeBm: 2,
				bmRelevant: 3,
				numQueries: 12,
				pageStay: 23.53,
				queryEntropy: 1.27125,
				totalCover: 6,
				totalModQuery: 3,
				usfCover: 8,
				writingTime: 32,
			},
			{
				cEffectiveness: 0,
				f1: 0.5,
				precision: 1,
				qEffectiveness: 0,
				recall: 1,
				score: 5,
				/*----------*/
				activeBm: 0,
				bmRelevant: 0,
				numQueries: 7,
				pageStay: 30.10,
				queryEntropy: 1.16289,
				totalCover: 12,
				totalModQuery: 8,
				usfCover: 6,
				writingTime: 21,
			}																																																															
		]
	}
}

export default queryResults;